# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(917, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777201, 16777215))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout = QtGui.QFormLayout(self.frame_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.frame = QtGui.QFrame(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.RaioUnidLabel_3 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.RaioUnidLabel_3.setFont(font)
        self.RaioUnidLabel_3.setObjectName(_fromUtf8("RaioUnidLabel_3"))
        self.gridLayout_6.addWidget(self.RaioUnidLabel_3, 1, 3, 1, 1)
        self.VazaoUnidLabel_2 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.VazaoUnidLabel_2.setFont(font)
        self.VazaoUnidLabel_2.setObjectName(_fromUtf8("VazaoUnidLabel_2"))
        self.gridLayout_6.addWidget(self.VazaoUnidLabel_2, 0, 3, 1, 1)
        self.RaioUnidLabel_4 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.RaioUnidLabel_4.setFont(font)
        self.RaioUnidLabel_4.setObjectName(_fromUtf8("RaioUnidLabel_4"))
        self.gridLayout_6.addWidget(self.RaioUnidLabel_4, 2, 3, 1, 1)
        self.Rugosidadesimblabel_2 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Rugosidadesimblabel_2.setFont(font)
        self.Rugosidadesimblabel_2.setObjectName(_fromUtf8("Rugosidadesimblabel_2"))
        self.gridLayout_6.addWidget(self.Rugosidadesimblabel_2, 3, 3, 1, 1)
        self.RugosidadeLabel = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.RugosidadeLabel.setFont(font)
        self.RugosidadeLabel.setObjectName(_fromUtf8("RugosidadeLabel"))
        self.gridLayout_6.addWidget(self.RugosidadeLabel, 3, 0, 1, 1)
        self.RugosidadeLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.RugosidadeLineEdit.setFont(font)
        self.RugosidadeLineEdit.setText(_fromUtf8(""))
        self.RugosidadeLineEdit.setObjectName(_fromUtf8("RugosidadeLineEdit"))
        self.gridLayout_6.addWidget(self.RugosidadeLineEdit, 3, 1, 1, 2)
        self.RaioLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.RaioLineEdit.setFont(font)
        self.RaioLineEdit.setText(_fromUtf8(""))
        self.RaioLineEdit.setObjectName(_fromUtf8("RaioLineEdit"))
        self.gridLayout_6.addWidget(self.RaioLineEdit, 1, 1, 1, 2)
        self.AreaLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.AreaLineEdit.setFont(font)
        self.AreaLineEdit.setText(_fromUtf8(""))
        self.AreaLineEdit.setObjectName(_fromUtf8("AreaLineEdit"))
        self.gridLayout_6.addWidget(self.AreaLineEdit, 2, 1, 1, 2)
        self.VazaoLabel = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.VazaoLabel.setFont(font)
        self.VazaoLabel.setObjectName(_fromUtf8("VazaoLabel"))
        self.gridLayout_6.addWidget(self.VazaoLabel, 0, 0, 1, 1)
        self.AreaLabel = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.AreaLabel.setFont(font)
        self.AreaLabel.setObjectName(_fromUtf8("AreaLabel"))
        self.gridLayout_6.addWidget(self.AreaLabel, 2, 0, 1, 1)
        self.RaioLabel = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.RaioLabel.setFont(font)
        self.RaioLabel.setObjectName(_fromUtf8("RaioLabel"))
        self.gridLayout_6.addWidget(self.RaioLabel, 1, 0, 1, 1)
        self.CalcularDeclivPushButton = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.CalcularDeclivPushButton.setFont(font)
        self.CalcularDeclivPushButton.setObjectName(_fromUtf8("CalcularDeclivPushButton"))
        self.gridLayout_6.addWidget(self.CalcularDeclivPushButton, 4, 0, 1, 1)
        self.VazaoLineEdit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.VazaoLineEdit.setFont(font)
        self.VazaoLineEdit.setText(_fromUtf8(""))
        self.VazaoLineEdit.setObjectName(_fromUtf8("VazaoLineEdit"))
        self.gridLayout_6.addWidget(self.VazaoLineEdit, 0, 1, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.frame)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.ProfLineEdit = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.ProfLineEdit.setFont(font)
        self.ProfLineEdit.setText(_fromUtf8(""))
        self.ProfLineEdit.setObjectName(_fromUtf8("ProfLineEdit"))
        self.gridLayout_9.addWidget(self.ProfLineEdit, 5, 1, 1, 1)
        self.LarguraLineEdit = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.LarguraLineEdit.setFont(font)
        self.LarguraLineEdit.setText(_fromUtf8(""))
        self.LarguraLineEdit.setObjectName(_fromUtf8("LarguraLineEdit"))
        self.gridLayout_9.addWidget(self.LarguraLineEdit, 4, 1, 1, 1)
        self.LocalLineEdit = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.LocalLineEdit.setFont(font)
        self.LocalLineEdit.setText(_fromUtf8(""))
        self.LocalLineEdit.setObjectName(_fromUtf8("LocalLineEdit"))
        self.gridLayout_9.addWidget(self.LocalLineEdit, 1, 1, 1, 1)
        self.DateEdit = QtGui.QDateEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.DateEdit.setFont(font)
        self.DateEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.DateEdit.setObjectName(_fromUtf8("DateEdit"))
        self.gridLayout_9.addWidget(self.DateEdit, 2, 1, 1, 1)
        self.ProfUnidLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.ProfUnidLabel.setFont(font)
        self.ProfUnidLabel.setObjectName(_fromUtf8("ProfUnidLabel"))
        self.gridLayout_9.addWidget(self.ProfUnidLabel, 5, 2, 1, 1)
        self.LarguraLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.LarguraLabel.setFont(font)
        self.LarguraLabel.setObjectName(_fromUtf8("LarguraLabel"))
        self.gridLayout_9.addWidget(self.LarguraLabel, 4, 0, 1, 1)
        self.LarguraUnidLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.LarguraUnidLabel.setFont(font)
        self.LarguraUnidLabel.setObjectName(_fromUtf8("LarguraUnidLabel"))
        self.gridLayout_9.addWidget(self.LarguraUnidLabel, 4, 2, 1, 1)
        self.D50Label = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.D50Label.setFont(font)
        self.D50Label.setObjectName(_fromUtf8("D50Label"))
        self.gridLayout_9.addWidget(self.D50Label, 9, 0, 1, 1)
        self.TempLineEdit = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.TempLineEdit.setFont(font)
        self.TempLineEdit.setText(_fromUtf8(""))
        self.TempLineEdit.setObjectName(_fromUtf8("TempLineEdit"))
        self.gridLayout_9.addWidget(self.TempLineEdit, 7, 1, 1, 1)
        self.TempUnidLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.TempUnidLabel.setFont(font)
        self.TempUnidLabel.setObjectName(_fromUtf8("TempUnidLabel"))
        self.gridLayout_9.addWidget(self.TempUnidLabel, 7, 2, 1, 1)
        self.SIngRadioButton = QtGui.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.SIngRadioButton.setFont(font)
        self.SIngRadioButton.setObjectName(_fromUtf8("SIngRadioButton"))
        self.gridLayout_9.addWidget(self.SIngRadioButton, 3, 1, 1, 1)
        self.D35LineEdit = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.D35LineEdit.setFont(font)
        self.D35LineEdit.setText(_fromUtf8(""))
        self.D35LineEdit.setObjectName(_fromUtf8("D35LineEdit"))
        self.gridLayout_9.addWidget(self.D35LineEdit, 8, 1, 1, 1)
        self.VelocLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.VelocLabel.setFont(font)
        self.VelocLabel.setObjectName(_fromUtf8("VelocLabel"))
        self.gridLayout_9.addWidget(self.VelocLabel, 6, 0, 1, 1)
        self.DeclivLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.DeclivLabel.setFont(font)
        self.DeclivLabel.setObjectName(_fromUtf8("DeclivLabel"))
        self.gridLayout_9.addWidget(self.DeclivLabel, 12, 0, 1, 1)
        self.D35Label = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.D35Label.setFont(font)
        self.D35Label.setObjectName(_fromUtf8("D35Label"))
        self.gridLayout_9.addWidget(self.D35Label, 8, 0, 1, 1)
        self.D65Label = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.D65Label.setFont(font)
        self.D65Label.setObjectName(_fromUtf8("D65Label"))
        self.gridLayout_9.addWidget(self.D65Label, 10, 0, 1, 1)
        self.SIntRadioButton = QtGui.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.SIntRadioButton.setFont(font)
        self.SIntRadioButton.setObjectName(_fromUtf8("SIntRadioButton"))
        self.gridLayout_9.addWidget(self.SIntRadioButton, 3, 0, 1, 1)
        self.TempLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.TempLabel.setFont(font)
        self.TempLabel.setObjectName(_fromUtf8("TempLabel"))
        self.gridLayout_9.addWidget(self.TempLabel, 7, 0, 1, 1)
        self.DataLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.DataLabel.setFont(font)
        self.DataLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DataLabel.setObjectName(_fromUtf8("DataLabel"))
        self.gridLayout_9.addWidget(self.DataLabel, 2, 0, 1, 1)
        self.ProfLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.ProfLabel.setFont(font)
        self.ProfLabel.setObjectName(_fromUtf8("ProfLabel"))
        self.gridLayout_9.addWidget(self.ProfLabel, 5, 0, 1, 1)
        self.LocalLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.LocalLabel.setFont(font)
        self.LocalLabel.setObjectName(_fromUtf8("LocalLabel"))
        self.gridLayout_9.addWidget(self.LocalLabel, 1, 0, 1, 1)
        self.D90Label = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.D90Label.setFont(font)
        self.D90Label.setObjectName(_fromUtf8("D90Label"))
        self.gridLayout_9.addWidget(self.D90Label, 11, 0, 1, 1)
        self.D50LineEdit = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.D50LineEdit.setFont(font)
        self.D50LineEdit.setText(_fromUtf8(""))
        self.D50LineEdit.setObjectName(_fromUtf8("D50LineEdit"))
        self.gridLayout_9.addWidget(self.D50LineEdit, 9, 1, 1, 1)
        self.VelocLineEdit = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.VelocLineEdit.setFont(font)
        self.VelocLineEdit.setText(_fromUtf8(""))
        self.VelocLineEdit.setObjectName(_fromUtf8("VelocLineEdit"))
        self.gridLayout_9.addWidget(self.VelocLineEdit, 6, 1, 1, 1)
        self.D90UnidLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.D90UnidLabel.setFont(font)
        self.D90UnidLabel.setObjectName(_fromUtf8("D90UnidLabel"))
        self.gridLayout_9.addWidget(self.D90UnidLabel, 11, 2, 1, 1)
        self.D65UnidLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.D65UnidLabel.setFont(font)
        self.D65UnidLabel.setObjectName(_fromUtf8("D65UnidLabel"))
        self.gridLayout_9.addWidget(self.D65UnidLabel, 10, 2, 1, 1)
        self.D65LineEdit = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.D65LineEdit.setFont(font)
        self.D65LineEdit.setText(_fromUtf8(""))
        self.D65LineEdit.setObjectName(_fromUtf8("D65LineEdit"))
        self.gridLayout_9.addWidget(self.D65LineEdit, 10, 1, 1, 1)
        self.DeclivLineEdit = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.DeclivLineEdit.setFont(font)
        self.DeclivLineEdit.setObjectName(_fromUtf8("DeclivLineEdit"))
        self.gridLayout_9.addWidget(self.DeclivLineEdit, 12, 1, 1, 1)
        self.VelocUnidLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.VelocUnidLabel.setFont(font)
        self.VelocUnidLabel.setObjectName(_fromUtf8("VelocUnidLabel"))
        self.gridLayout_9.addWidget(self.VelocUnidLabel, 6, 2, 1, 1)
        self.D50UnidLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.D50UnidLabel.setFont(font)
        self.D50UnidLabel.setObjectName(_fromUtf8("D50UnidLabel"))
        self.gridLayout_9.addWidget(self.D50UnidLabel, 9, 2, 1, 1)
        self.D90LineEdit = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.D90LineEdit.setFont(font)
        self.D90LineEdit.setText(_fromUtf8(""))
        self.D90LineEdit.setObjectName(_fromUtf8("D90LineEdit"))
        self.gridLayout_9.addWidget(self.D90LineEdit, 11, 1, 1, 1)
        self.D35UnidLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.D35UnidLabel.setFont(font)
        self.D35UnidLabel.setObjectName(_fromUtf8("D35UnidLabel"))
        self.gridLayout_9.addWidget(self.D35UnidLabel, 8, 2, 1, 1)
        self.DeclivUnidLabel = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.DeclivUnidLabel.setFont(font)
        self.DeclivUnidLabel.setObjectName(_fromUtf8("DeclivUnidLabel"))
        self.gridLayout_9.addWidget(self.DeclivUnidLabel, 12, 2, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.gridLayout_9)
        self.gridLayout_5.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.frame_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.FracoesDeTamanho = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.FracoesDeTamanho.setFont(font)
        self.FracoesDeTamanho.setObjectName(_fromUtf8("FracoesDeTamanho"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.FracoesDeTamanho)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.Faixa11LineEdit = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Faixa11LineEdit.sizePolicy().hasHeightForWidth())
        self.Faixa11LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa11LineEdit.setFont(font)
        self.Faixa11LineEdit.setText(_fromUtf8(""))
        self.Faixa11LineEdit.setObjectName(_fromUtf8("Faixa11LineEdit"))
        self.gridLayout_11.addWidget(self.Faixa11LineEdit, 11, 2, 1, 1)
        self.Faixa8Label = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa8Label.setFont(font)
        self.Faixa8Label.setObjectName(_fromUtf8("Faixa8Label"))
        self.gridLayout_11.addWidget(self.Faixa8Label, 8, 0, 1, 1)
        self.Faixa3Label = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa3Label.setFont(font)
        self.Faixa3Label.setObjectName(_fromUtf8("Faixa3Label"))
        self.gridLayout_11.addWidget(self.Faixa3Label, 3, 0, 1, 1)
        self.Faixa1Label = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa1Label.setFont(font)
        self.Faixa1Label.setObjectName(_fromUtf8("Faixa1Label"))
        self.gridLayout_11.addWidget(self.Faixa1Label, 1, 0, 1, 1)
        self.Faixa2Label = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa2Label.setFont(font)
        self.Faixa2Label.setObjectName(_fromUtf8("Faixa2Label"))
        self.gridLayout_11.addWidget(self.Faixa2Label, 2, 0, 1, 1)
        self.Faixa7Label = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa7Label.setFont(font)
        self.Faixa7Label.setObjectName(_fromUtf8("Faixa7Label"))
        self.gridLayout_11.addWidget(self.Faixa7Label, 7, 0, 1, 1)
        self.Faixa5Label = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa5Label.setFont(font)
        self.Faixa5Label.setObjectName(_fromUtf8("Faixa5Label"))
        self.gridLayout_11.addWidget(self.Faixa5Label, 5, 0, 1, 1)
        self.Faixa6Label = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa6Label.setFont(font)
        self.Faixa6Label.setObjectName(_fromUtf8("Faixa6Label"))
        self.gridLayout_11.addWidget(self.Faixa6Label, 6, 0, 1, 1)
        self.Faixa4Label = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa4Label.setFont(font)
        self.Faixa4Label.setObjectName(_fromUtf8("Faixa4Label"))
        self.gridLayout_11.addWidget(self.Faixa4Label, 4, 0, 1, 1)
        self.Faixa9Label = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa9Label.setFont(font)
        self.Faixa9Label.setObjectName(_fromUtf8("Faixa9Label"))
        self.gridLayout_11.addWidget(self.Faixa9Label, 9, 0, 1, 1)
        self.Faixa10Label = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa10Label.setFont(font)
        self.Faixa10Label.setObjectName(_fromUtf8("Faixa10Label"))
        self.gridLayout_11.addWidget(self.Faixa10Label, 10, 0, 1, 1)
        self.Faixa11Label = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa11Label.setFont(font)
        self.Faixa11Label.setObjectName(_fromUtf8("Faixa11Label"))
        self.gridLayout_11.addWidget(self.Faixa11Label, 11, 0, 1, 1)
        self.Faixa1LineEdit = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Faixa1LineEdit.sizePolicy().hasHeightForWidth())
        self.Faixa1LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa1LineEdit.setFont(font)
        self.Faixa1LineEdit.setText(_fromUtf8(""))
        self.Faixa1LineEdit.setObjectName(_fromUtf8("Faixa1LineEdit"))
        self.gridLayout_11.addWidget(self.Faixa1LineEdit, 1, 2, 1, 1)
        self.Faixa2LineEdit = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Faixa2LineEdit.sizePolicy().hasHeightForWidth())
        self.Faixa2LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa2LineEdit.setFont(font)
        self.Faixa2LineEdit.setText(_fromUtf8(""))
        self.Faixa2LineEdit.setObjectName(_fromUtf8("Faixa2LineEdit"))
        self.gridLayout_11.addWidget(self.Faixa2LineEdit, 2, 2, 1, 1)
        self.Faixa3LineEdit = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Faixa3LineEdit.sizePolicy().hasHeightForWidth())
        self.Faixa3LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa3LineEdit.setFont(font)
        self.Faixa3LineEdit.setText(_fromUtf8(""))
        self.Faixa3LineEdit.setObjectName(_fromUtf8("Faixa3LineEdit"))
        self.gridLayout_11.addWidget(self.Faixa3LineEdit, 3, 2, 1, 1)
        self.Faixa4LineEdit = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Faixa4LineEdit.sizePolicy().hasHeightForWidth())
        self.Faixa4LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa4LineEdit.setFont(font)
        self.Faixa4LineEdit.setText(_fromUtf8(""))
        self.Faixa4LineEdit.setObjectName(_fromUtf8("Faixa4LineEdit"))
        self.gridLayout_11.addWidget(self.Faixa4LineEdit, 4, 2, 1, 1)
        self.Faixa5LineEdit = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Faixa5LineEdit.sizePolicy().hasHeightForWidth())
        self.Faixa5LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa5LineEdit.setFont(font)
        self.Faixa5LineEdit.setText(_fromUtf8(""))
        self.Faixa5LineEdit.setObjectName(_fromUtf8("Faixa5LineEdit"))
        self.gridLayout_11.addWidget(self.Faixa5LineEdit, 5, 2, 1, 1)
        self.Faixa6LineEdit = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Faixa6LineEdit.sizePolicy().hasHeightForWidth())
        self.Faixa6LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa6LineEdit.setFont(font)
        self.Faixa6LineEdit.setText(_fromUtf8(""))
        self.Faixa6LineEdit.setObjectName(_fromUtf8("Faixa6LineEdit"))
        self.gridLayout_11.addWidget(self.Faixa6LineEdit, 6, 2, 1, 1)
        self.Faixa7LineEdit = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Faixa7LineEdit.sizePolicy().hasHeightForWidth())
        self.Faixa7LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa7LineEdit.setFont(font)
        self.Faixa7LineEdit.setText(_fromUtf8(""))
        self.Faixa7LineEdit.setObjectName(_fromUtf8("Faixa7LineEdit"))
        self.gridLayout_11.addWidget(self.Faixa7LineEdit, 7, 2, 1, 1)
        self.Faixa8LineEdit = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Faixa8LineEdit.sizePolicy().hasHeightForWidth())
        self.Faixa8LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa8LineEdit.setFont(font)
        self.Faixa8LineEdit.setText(_fromUtf8(""))
        self.Faixa8LineEdit.setObjectName(_fromUtf8("Faixa8LineEdit"))
        self.gridLayout_11.addWidget(self.Faixa8LineEdit, 8, 2, 1, 1)
        self.Faixa9LineEdit = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Faixa9LineEdit.sizePolicy().hasHeightForWidth())
        self.Faixa9LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa9LineEdit.setFont(font)
        self.Faixa9LineEdit.setText(_fromUtf8(""))
        self.Faixa9LineEdit.setObjectName(_fromUtf8("Faixa9LineEdit"))
        self.gridLayout_11.addWidget(self.Faixa9LineEdit, 9, 2, 1, 1)
        self.Faixa10LineEdit = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Faixa10LineEdit.sizePolicy().hasHeightForWidth())
        self.Faixa10LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa10LineEdit.setFont(font)
        self.Faixa10LineEdit.setText(_fromUtf8(""))
        self.Faixa10LineEdit.setObjectName(_fromUtf8("Faixa10LineEdit"))
        self.gridLayout_11.addWidget(self.Faixa10LineEdit, 10, 2, 1, 1)
        self.Faixa1UnidLabel = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa1UnidLabel.setFont(font)
        self.Faixa1UnidLabel.setObjectName(_fromUtf8("Faixa1UnidLabel"))
        self.gridLayout_11.addWidget(self.Faixa1UnidLabel, 1, 3, 1, 1)
        self.Faixa2UnidLabel = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa2UnidLabel.setFont(font)
        self.Faixa2UnidLabel.setObjectName(_fromUtf8("Faixa2UnidLabel"))
        self.gridLayout_11.addWidget(self.Faixa2UnidLabel, 2, 3, 1, 1)
        self.Faixa3UnidLabel = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa3UnidLabel.setFont(font)
        self.Faixa3UnidLabel.setObjectName(_fromUtf8("Faixa3UnidLabel"))
        self.gridLayout_11.addWidget(self.Faixa3UnidLabel, 3, 3, 1, 1)
        self.Faixa4UnidLabel = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa4UnidLabel.setFont(font)
        self.Faixa4UnidLabel.setObjectName(_fromUtf8("Faixa4UnidLabel"))
        self.gridLayout_11.addWidget(self.Faixa4UnidLabel, 4, 3, 1, 1)
        self.Faixa5UnidLabel = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa5UnidLabel.setFont(font)
        self.Faixa5UnidLabel.setObjectName(_fromUtf8("Faixa5UnidLabel"))
        self.gridLayout_11.addWidget(self.Faixa5UnidLabel, 5, 3, 1, 1)
        self.Faixa6UnidLabel = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa6UnidLabel.setFont(font)
        self.Faixa6UnidLabel.setObjectName(_fromUtf8("Faixa6UnidLabel"))
        self.gridLayout_11.addWidget(self.Faixa6UnidLabel, 6, 3, 1, 1)
        self.Faixa7UnidLabel = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa7UnidLabel.setFont(font)
        self.Faixa7UnidLabel.setObjectName(_fromUtf8("Faixa7UnidLabel"))
        self.gridLayout_11.addWidget(self.Faixa7UnidLabel, 7, 3, 1, 1)
        self.Faixa8UnidLabel = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa8UnidLabel.setFont(font)
        self.Faixa8UnidLabel.setObjectName(_fromUtf8("Faixa8UnidLabel"))
        self.gridLayout_11.addWidget(self.Faixa8UnidLabel, 8, 3, 1, 1)
        self.Faixa9UnidLabel = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa9UnidLabel.setFont(font)
        self.Faixa9UnidLabel.setObjectName(_fromUtf8("Faixa9UnidLabel"))
        self.gridLayout_11.addWidget(self.Faixa9UnidLabel, 9, 3, 1, 1)
        self.Faixa10UnidLabel = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa10UnidLabel.setFont(font)
        self.Faixa10UnidLabel.setObjectName(_fromUtf8("Faixa10UnidLabel"))
        self.gridLayout_11.addWidget(self.Faixa10UnidLabel, 10, 3, 1, 1)
        self.Faixa11UnidLabel = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.Faixa11UnidLabel.setFont(font)
        self.Faixa11UnidLabel.setObjectName(_fromUtf8("Faixa11UnidLabel"))
        self.gridLayout_11.addWidget(self.Faixa11UnidLabel, 11, 3, 1, 1)
        self.formLayout_4.setLayout(2, QtGui.QFormLayout.LabelRole, self.gridLayout_11)
        self.gridLayout_5.addWidget(self.frame_4, 1, 1, 1, 1)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_3, 3, 1, 1, 1)
        self.CalcularPushButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.CalcularPushButton.setFont(font)
        self.CalcularPushButton.setObjectName(_fromUtf8("CalcularPushButton"))
        self.gridLayout_5.addWidget(self.CalcularPushButton, 3, 2, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 3, 0, 1, 1)
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame_5)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.EngelundeHansenCheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.EngelundeHansenCheckBox.setFont(font)
        self.EngelundeHansenCheckBox.setObjectName(_fromUtf8("EngelundeHansenCheckBox"))
        self.gridLayout_10.addWidget(self.EngelundeHansenCheckBox, 3, 0, 1, 1)
        self.YangMixCheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.YangMixCheckBox.setFont(font)
        self.YangMixCheckBox.setObjectName(_fromUtf8("YangMixCheckBox"))
        self.gridLayout_10.addWidget(self.YangMixCheckBox, 11, 0, 1, 1)
        self.ColbyCheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.ColbyCheckBox.setFont(font)
        self.ColbyCheckBox.setObjectName(_fromUtf8("ColbyCheckBox"))
        self.gridLayout_10.addWidget(self.ColbyCheckBox, 4, 0, 1, 1)
        self.RottnerCheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.RottnerCheckBox.setFont(font)
        self.RottnerCheckBox.setObjectName(_fromUtf8("RottnerCheckBox"))
        self.gridLayout_10.addWidget(self.RottnerCheckBox, 16, 0, 1, 1)
        self.YangGravelD50CheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.YangGravelD50CheckBox.setFont(font)
        self.YangGravelD50CheckBox.setObjectName(_fromUtf8("YangGravelD50CheckBox"))
        self.gridLayout_10.addWidget(self.YangGravelD50CheckBox, 9, 0, 1, 1)
        self.YangSandD50CheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.YangSandD50CheckBox.setFont(font)
        self.YangSandD50CheckBox.setObjectName(_fromUtf8("YangSandD50CheckBox"))
        self.gridLayout_10.addWidget(self.YangSandD50CheckBox, 7, 0, 1, 1)
        self.YangSandFTCheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.YangSandFTCheckBox.setFont(font)
        self.YangSandFTCheckBox.setObjectName(_fromUtf8("YangSandFTCheckBox"))
        self.gridLayout_10.addWidget(self.YangSandFTCheckBox, 8, 0, 1, 1)
        self.MeyerPeterICheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.MeyerPeterICheckBox.setFont(font)
        self.MeyerPeterICheckBox.setObjectName(_fromUtf8("MeyerPeterICheckBox"))
        self.gridLayout_10.addWidget(self.MeyerPeterICheckBox, 15, 0, 1, 1)
        self.LaursenCheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.LaursenCheckBox.setFont(font)
        self.LaursenCheckBox.setObjectName(_fromUtf8("LaursenCheckBox"))
        self.gridLayout_10.addWidget(self.LaursenCheckBox, 2, 0, 1, 1)
        self.KallinskeCheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.KallinskeCheckBox.setFont(font)
        self.KallinskeCheckBox.setObjectName(_fromUtf8("KallinskeCheckBox"))
        self.gridLayout_10.addWidget(self.KallinskeCheckBox, 14, 0, 1, 1)
        self.YangGravelFTCheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.YangGravelFTCheckBox.setFont(font)
        self.YangGravelFTCheckBox.setObjectName(_fromUtf8("YangGravelFTCheckBox"))
        self.gridLayout_10.addWidget(self.YangGravelFTCheckBox, 10, 0, 1, 1)
        self.AckersWhiteD35CheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.AckersWhiteD35CheckBox.setFont(font)
        self.AckersWhiteD35CheckBox.setObjectName(_fromUtf8("AckersWhiteD35CheckBox"))
        self.gridLayout_10.addWidget(self.AckersWhiteD35CheckBox, 6, 0, 1, 1)
        self.SchoklitschCheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.SchoklitschCheckBox.setFont(font)
        self.SchoklitschCheckBox.setObjectName(_fromUtf8("SchoklitschCheckBox"))
        self.gridLayout_10.addWidget(self.SchoklitschCheckBox, 13, 0, 1, 1)
        self.ArrasteCheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ArrasteCheckBox.setFont(font)
        self.ArrasteCheckBox.setStyleSheet(_fromUtf8("background-color: rgb(198, 209, 255);"))
        self.ArrasteCheckBox.setObjectName(_fromUtf8("ArrasteCheckBox"))
        self.gridLayout_10.addWidget(self.ArrasteCheckBox, 12, 0, 1, 1)
        self.AckersWhiteD50CheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.AckersWhiteD50CheckBox.setFont(font)
        self.AckersWhiteD50CheckBox.setObjectName(_fromUtf8("AckersWhiteD50CheckBox"))
        self.gridLayout_10.addWidget(self.AckersWhiteD50CheckBox, 5, 0, 1, 1)
        self.ArrasteSuspensaoCheckBox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.ArrasteSuspensaoCheckBox.setFont(font)
        self.ArrasteSuspensaoCheckBox.setAutoFillBackground(False)
        self.ArrasteSuspensaoCheckBox.setStyleSheet(_fromUtf8("background-color: rgb(198, 209, 255);"))
        self.ArrasteSuspensaoCheckBox.setObjectName(_fromUtf8("ArrasteSuspensaoCheckBox"))
        self.gridLayout_10.addWidget(self.ArrasteSuspensaoCheckBox, 1, 0, 1, 1)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.LabelRole, self.gridLayout_10)
        self.gridLayout_5.addWidget(self.frame_5, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 917, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName(_fromUtf8("menuAjuda"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNovo = QtGui.QAction(MainWindow)
        self.actionNovo.setObjectName(_fromUtf8("actionNovo"))
        self.actionAbrir = QtGui.QAction(MainWindow)
        self.actionAbrir.setObjectName(_fromUtf8("actionAbrir"))
        self.actionSalvar = QtGui.QAction(MainWindow)
        self.actionSalvar.setObjectName(_fromUtf8("actionSalvar"))
        self.actionManual_Sedim_2_0 = QtGui.QAction(MainWindow)
        self.actionManual_Sedim_2_0.setObjectName(_fromUtf8("actionManual_Sedim_2_0"))
        self.actionSobre = QtGui.QAction(MainWindow)
        self.actionSobre.setObjectName(_fromUtf8("actionSobre"))
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.menuArquivo.addAction(self.actionNovo)
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addAction(self.actionSalvar)
        self.menuArquivo.addAction(self.actionSair)
        self.menuAjuda.addAction(self.actionManual_Sedim_2_0)
        self.menuAjuda.addAction(self.actionSobre)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SEDIM 2.0", None))
        self.RaioUnidLabel_3.setText(_translate("MainWindow", "m", None))
        self.VazaoUnidLabel_2.setText(_translate("MainWindow", "m3/s", None))
        self.RaioUnidLabel_4.setText(_translate("MainWindow", "m2", None))
        self.Rugosidadesimblabel_2.setText(_translate("MainWindow", "(n)", None))
        self.RugosidadeLabel.setText(_translate("MainWindow", "Coeficiente de Rugosidade", None))
        self.VazaoLabel.setText(_translate("MainWindow", "Descarga Líquida", None))
        self.AreaLabel.setText(_translate("MainWindow", "Área da Seção", None))
        self.RaioLabel.setText(_translate("MainWindow", "Raio Hidráulico", None))
        self.CalcularDeclivPushButton.setText(_translate("MainWindow", "Calcular Declividade", None))
        self.DateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy", None))
        self.ProfUnidLabel.setText(_translate("MainWindow", "m", None))
        self.LarguraLabel.setText(_translate("MainWindow", "Largura:", None))
        self.LarguraUnidLabel.setText(_translate("MainWindow", "m", None))
        self.D50Label.setText(_translate("MainWindow", "D50:", None))
        self.TempUnidLabel.setText(_translate("MainWindow", "°C", None))
        self.SIngRadioButton.setText(_translate("MainWindow", "Sistema Inglês", None))
        self.VelocLabel.setText(_translate("MainWindow", "Velocidade média: ", None))
        self.DeclivLabel.setText(_translate("MainWindow", "Declividade:", None))
        self.D35Label.setText(_translate("MainWindow", "D35:", None))
        self.D65Label.setText(_translate("MainWindow", "D65:", None))
        self.SIntRadioButton.setText(_translate("MainWindow", "Sistema Métrico", None))
        self.TempLabel.setText(_translate("MainWindow", "Temperatura:", None))
        self.DataLabel.setText(_translate("MainWindow", "Data:", None))
        self.ProfLabel.setText(_translate("MainWindow", "Profundidade média:", None))
        self.LocalLabel.setText(_translate("MainWindow", "Local", None))
        self.D90Label.setText(_translate("MainWindow", "D90:", None))
        self.D90UnidLabel.setText(_translate("MainWindow", "mm", None))
        self.D65UnidLabel.setText(_translate("MainWindow", "mm", None))
        self.VelocUnidLabel.setText(_translate("MainWindow", "m/s", None))
        self.D50UnidLabel.setText(_translate("MainWindow", "mm", None))
        self.D35UnidLabel.setText(_translate("MainWindow", "mm", None))
        self.DeclivUnidLabel.setText(_translate("MainWindow", "m/m", None))
        self.FracoesDeTamanho.setText(_translate("MainWindow", "Dados das frações de tamanho em porcentagem:", None))
        self.Faixa8Label.setText(_translate("MainWindow", "4,000 a 8,000 mm:", None))
        self.Faixa3Label.setText(_translate("MainWindow", "0,125 a 0,250 mm:", None))
        self.Faixa1Label.setText(_translate("MainWindow", "0,000 a 0,062 mm:", None))
        self.Faixa2Label.setText(_translate("MainWindow", "0,062 a 0,125 mm:", None))
        self.Faixa7Label.setText(_translate("MainWindow", "2,000 a 4,000 mm:", None))
        self.Faixa5Label.setText(_translate("MainWindow", "0,500 a 1,000 mm:", None))
        self.Faixa6Label.setText(_translate("MainWindow", "1,000 a 2,000 mm:", None))
        self.Faixa4Label.setText(_translate("MainWindow", "0,250 a 0,500 mm:", None))
        self.Faixa9Label.setText(_translate("MainWindow", "8,000 a 16,00 mm:", None))
        self.Faixa10Label.setText(_translate("MainWindow", "16,00 a 32,00 mm:", None))
        self.Faixa11Label.setText(_translate("MainWindow", "32,00 a 64,00 mm:", None))
        self.Faixa1UnidLabel.setText(_translate("MainWindow", "%", None))
        self.Faixa2UnidLabel.setText(_translate("MainWindow", "%", None))
        self.Faixa3UnidLabel.setText(_translate("MainWindow", "%", None))
        self.Faixa4UnidLabel.setText(_translate("MainWindow", "%", None))
        self.Faixa5UnidLabel.setText(_translate("MainWindow", "%", None))
        self.Faixa6UnidLabel.setText(_translate("MainWindow", "%", None))
        self.Faixa7UnidLabel.setText(_translate("MainWindow", "%", None))
        self.Faixa8UnidLabel.setText(_translate("MainWindow", "%", None))
        self.Faixa9UnidLabel.setText(_translate("MainWindow", "%", None))
        self.Faixa10UnidLabel.setText(_translate("MainWindow", "%", None))
        self.Faixa11UnidLabel.setText(_translate("MainWindow", "%", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Prefix/PGEB UFF.png\"/></p></body></html>", None))
        self.CalcularPushButton.setText(_translate("MainWindow", "Calcular", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Prefix/logouffcompleto.png\"/></p></body></html>", None))
        self.EngelundeHansenCheckBox.setText(_translate("MainWindow", "Engelund e Hansen", None))
        self.YangMixCheckBox.setText(_translate("MainWindow", "Yang Sand e Gravel", None))
        self.ColbyCheckBox.setText(_translate("MainWindow", "Colby", None))
        self.RottnerCheckBox.setText(_translate("MainWindow", "Rottner", None))
        self.YangGravelD50CheckBox.setText(_translate("MainWindow", "Yang Gravel (D50)", None))
        self.YangSandD50CheckBox.setText(_translate("MainWindow", "Yang Sand (D50)", None))
        self.YangSandFTCheckBox.setText(_translate("MainWindow", "Yang Sand (FT)", None))
        self.MeyerPeterICheckBox.setText(_translate("MainWindow", "Meyer-Peter e Muller I", None))
        self.LaursenCheckBox.setText(_translate("MainWindow", "Laursen", None))
        self.KallinskeCheckBox.setText(_translate("MainWindow", "Kallinske", None))
        self.YangGravelFTCheckBox.setText(_translate("MainWindow", "Yang Gravel (FT)", None))
        self.AckersWhiteD35CheckBox.setText(_translate("MainWindow", "Ackers e White (D35)", None))
        self.SchoklitschCheckBox.setText(_translate("MainWindow", "Schoklitsch", None))
        self.ArrasteCheckBox.setText(_translate("MainWindow", "Arraste", None))
        self.AckersWhiteD50CheckBox.setText(_translate("MainWindow", "Ackers e White (D50)", None))
        self.ArrasteSuspensaoCheckBox.setText(_translate("MainWindow", "Arraste e Suspensão", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo", None))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda", None))
        self.actionNovo.setText(_translate("MainWindow", "Novo", None))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir", None))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar", None))
        self.actionManual_Sedim_2_0.setText(_translate("MainWindow", "Manual Sedim 2.0", None))
        self.actionSobre.setText(_translate("MainWindow", "Sobre", None))
        self.actionSair.setText(_translate("MainWindow", "Sair", None))

import resourcetest_rc
